# group_vars/all.yaml
dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - libffi-dev
  - libssl-dev

docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
docker_package: docker-ce
docker_compose_v2_url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64
