version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/backend/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  backend-data:
