version: '2.2'

services:
  frontend:
    build: ./client
    stdin_open: true
    image: client-image:v5
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yolo-network

  backend:
    build: ./backend
    image: my-test-app:latest
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/backend/data
    networks:
      - yolo-network
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/yolomy"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

volumes:
  backend-data:
  mongodb_data:
