---
- name: Test Playbook for Docker Compose Installation
  hosts: all
  become: yes
  tasks:
    - name: Install pip
      package:
        name: python3-pip
        state: present

    - name: Install Docker Compose using pip
      pip:
        name: docker-compose
        executable: pip3
        state: present

    - name: Verify Docker Compose installation
      command: docker-compose --version
