---
- name: Install Docker Compose using pip
  pip:
    name: docker-compose
    state: present
    extra_args: "--ignore-installed"
  tags: docker_compose

- name: Verify Docker Compose installation
  command: docker-compose --version
  tags: docker_compose

- name: Install Docker Compose v2
  get_url:
    url: "{{ docker_compose_v2_url }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  notify:
    - Restart Docker
  tags: docker_compose

- name: Use Docker Compose v2 to build and start containers
  community.docker.docker_compose_v2:
    project_src: /vagrant
    state: present
    build: always
    remove_orphans: yes
  tags: docker_compose
