---
- name: Install Docker Compose using pip
  pip:
    name: docker-compose
    state: present
    extra_args: "--ignore-installed"

- name: Verify Docker Compose installation
  command: docker-compose --version

- name: Install Docker Compose v2
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  notify:
    - Restart Docker

- name: Use Docker Compose v2 to build and start containers
  community.docker.docker_compose_v2:
    project_src: /vagrant
    state: present
    build: always
    remove_orphans: yes
