---
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
docker_compose_version: "v2.5.0"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
